### PR TITLE
Move i18n related files

### PR DESCRIPTION
**Pull request by mwjames**
refs #5

@kghbln FYI

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
This will not make TWN blow up?

**Comment by mwjames** [comment]
> This will not make TWN blow up?

This is why I pinged @kghbln.

**Comment by kghbln** [comment]
It will not blow up according to https://github.com/SemanticMediaWiki/SemanticSignup/issues/5#issuecomment-71544227. Thus I am pinging @raymondde to ask if he could do the necessary changes in the translation configuration for this extension. I believe that we will have to merge and sync the two repos within a day after he has done the change to avoid a possible mess.

**Comment by raymondde** [comment]
@kghbln Please merge first, then I can update the translatewiki.net configuration.

**Comment by kghbln** [comment]
Thanks a lot for your info! @JeroenDeDauw Could you merge and most importantly sync with the WMF repo and ping @raymondde afterwards so he knows that things happened for him to do the adjustments. Will be great.

**Comment by JeroenDeDauw** [comment]
@raymondde @kghbln merged into WMF mirror

**Comment by kghbln** [comment]
Great. Thanks to all of you!

**Comment by raymondde** [comment]
translatewiki.net config updated yesterday already: https://gerrit.wikimedia.org/r/#/c/191265/

**Comment by kghbln** [comment]
:+1:

**Pull request merged**
